# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build -- --prod --baseHref="https://indrajitbnikam.github.io/angular-tailwind-example/"

    # You may pin to the exact commit or the version.
    # uses: JamesIves/github-pages-deploy-action@54066045208a389f6e16e9030494962f8afb4dfc
    - uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        # Depending on the repository permissions you may need to provide the action with a GitHub personal access token instead of the provided GitHub token in order to deploy. This should be stored as a secret.
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # This is the branch you wish to deploy to, for example gh-pages or docs.
        BRANCH: gh-pages
        # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
        FOLDER: 'dist/angular-tailwind-example'
